/*
 * File name: ultrasonic.h
 *
 * Created on: 15 Oct 2021
 *
 * Author: Mina Sameh
 *
 * Description: Header file for the ultrasonic driver
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "gpio.h"
#include "ICU.h"
#include <util/delay.h> /* For the delay functions */


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
/* for the ultrasonic trigger pin*/
#define Ultrasonic_triggerPORT_ID PORTB_ID
#define Ultrasonic_triggerPIN_ID  PIN5_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 *
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.\
 * Set trigger pin initial output as low
 */
void Ultrasonic_init(void);

/*
 * Description :
 *
 * Send the Trigger pulse to the ultrasonic by writing a logic high signal for 20 micro seconds.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 *
 * Send the trigger pulse by calling Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 * Inputs: None
 * Return: (uint16) The measured distance in Centimeter
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 *
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
