/*
 *  File name: ultrasonic.c
 *
 *  Created on: 15 Oct 2021
 *
 *  Author: Mina Sameh
 *
 *  Description: Source file for the ultrasonic driver
 */
#include"std_types.h"
#include"common_macros.h"
#include"ultrasonic.h"

uint8  g_edgeCount = 0;
uint16 g_timeHigh = 0;

/*
 * Description :
 *
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.\
 * Set trigger pin initial output as low
 */
void Ultrasonic_init(void){
	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/* Initialize the ICU driver */
	Icu_init(&Icu_Config);
	/*Setup the direction for the trigger pin as output pin */
	GPIO_setupPinDirection(Ultrasonic_triggerPORT_ID, Ultrasonic_triggerPIN_ID, PIN_OUTPUT);
	GPIO_writePin(Ultrasonic_triggerPORT_ID, Ultrasonic_triggerPIN_ID, LOGIC_LOW);
}


/*
 * Description :
 *
 * Send the Trigger pulse to the ultrasonic by writing a logic high signal for 20 micro seconds.
 */
void Ultrasonic_Trigger(void){
	 GPIO_writePin(Ultrasonic_triggerPORT_ID, Ultrasonic_triggerPIN_ID, LOGIC_HIGH);
	 _delay_us(20);
	 GPIO_writePin(Ultrasonic_triggerPORT_ID, Ultrasonic_triggerPIN_ID, LOGIC_LOW);
}

/*
 * Description :
 *
 * Send the trigger pulse by calling Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 * Inputs: None
 * Return: (uint16) The measured distance in Centimeter
 */
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	return (g_timeHigh/58.8);
}

/*
 * Description :
 *
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void){

		g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_timeHigh = Icu_getInputCaptureValue();
			/* Detect rising edge */
			Icu_setEdgeDetectionType(RISING);
			/* Reset counter */
			g_edgeCount = 0;
		}
}


